# Generated by Django 3.2.9 on 2022-04-28 17:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sberapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('payments', 'payments'), ('charges', 'charges'), ('measurements', 'measurements')], max_length=20)),
                ('dt', models.DateTimeField(default=datetime.datetime(2022, 4, 28, 17, 22, 14, 352000))),
                ('sum', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sberapi.client')),
            ],
        ),
    ]
