# Generated by Django 3.2.9 on 2022-04-28 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sberapi', '0002_clientdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
