# Generated by Django 3.2.9 on 2022-04-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sberapi', '0004_client_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdata',
            name='client',
        ),
        migrations.AddField(
            model_name='clientdata',
            name='account_id',
            field=models.CharField(default='1001', max_length=20),
            preserve_default=False,
        ),
    ]
